/**
 * Embedded anime data (fallback for file:// protocol)
 * This allows the app to work when opened directly in a browser
 */
const ANIME_DATA = {
  "anime": [
    {
      "id": "frieren",
      "title": "Frieren: Beyond Journey's End",
      "cover": "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
      "year": 2023,
      "season": "Fall",
      "studio": "Madhouse",
      "source": "Manga",
      "genres": ["Adventure", "Drama", "Fantasy"],
      "themes": [],
      "demographic": "Shounen",
      "episodes": [
        { "episode": 1, "score": 4.4 },
        { "episode": 2, "score": 4.4 },
        { "episode": 3, "score": 4.4 },
        { "episode": 4, "score": 4.5 },
        { "episode": 5, "score": 4.5 },
        { "episode": 6, "score": 4.6 },
        { "episode": 7, "score": 4.6 },
        { "episode": 8, "score": 4.7 },
        { "episode": 9, "score": 4.7 },
        { "episode": 10, "score": 4.8 },
        { "episode": 11, "score": 4.6 },
        { "episode": 12, "score": 4.7 },
        { "episode": 13, "score": 4.5 },
        { "episode": 14, "score": 4.7 },
        { "episode": 15, "score": 4.7 },
        { "episode": 16, "score": 4.6 },
        { "episode": 17, "score": 4.6 },
        { "episode": 18, "score": 4.5 },
        { "episode": 19, "score": 4.6 },
        { "episode": 20, "score": 4.6 },
        { "episode": 21, "score": 4.7 },
        { "episode": 22, "score": 4.5 },
        { "episode": 23, "score": 4.7 },
        { "episode": 24, "score": 4.6 },
        { "episode": 25, "score": 4.7 },
        { "episode": 26, "score": 4.8 },
        { "episode": 27, "score": 4.8 },
        { "episode": 28, "score": 4.7 }
      ]
    },
    {
      "id": "5-toubun",
      "title": "The Quintessential Quintuplets",
      "cover": "https://cdn.myanimelist.net/images/anime/1819/97947.jpg",
      "year": 2019,
      "season": "Winter",
      "studio": "Tezuka Productions",
      "source": "Manga",
      "genres": ["Comedy", "Romance"],
      "themes": ["Harem", "School"],
      "demographic": "Shounen",
      "episodes": [
        { "episode": 1, "score": 4.2 },
        { "episode": 2, "score": 4.3 },
        { "episode": 3, "score": 4.1 },
        { "episode": 4, "score": 4.3 },
        { "episode": 5, "score": 4.4 },
        { "episode": 6, "score": 4.4 },
        { "episode": 7, "score": 4.5 },
        { "episode": 8, "score": 4.6 },
        { "episode": 9, "score": 4.5 },
        { "episode": 10, "score": 4.4 },
        { "episode": 11, "score": 4.6 },
        { "episode": 12, "score": 4.4 }
      ]
    },
    {
      "id": "oshi-no-ko",
      "title": "Oshi no Ko",
      "cover": "https://cdn.myanimelist.net/images/anime/1812/134736.jpg",
      "year": 2023,
      "season": "Spring",
      "studio": "Doga Kobo",
      "source": "Manga",
      "genres": ["Drama", "Award Winning"],
      "themes": ["Reincarnation", "Showbiz"],
      "demographic": "Seinen",
      "episodes": [
        { "episode": 1, "score": 4.7 },
        { "episode": 2, "score": 4.4 },
        { "episode": 3, "score": 4.4 },
        { "episode": 4, "score": 4.5 },
        { "episode": 5, "score": 4.4 },
        { "episode": 6, "score": 4.7 },
        { "episode": 7, "score": 4.7 },
        { "episode": 8, "score": 4.6 },
        { "episode": 9, "score": 4.5 },
        { "episode": 10, "score": 4.5 },
        { "episode": 11, "score": 4.6 }
      ]
    },
    {
      "id": "adachi-and-shimamura",
      "title": "Adachi and Shimamura",
      "cover": "https://cdn.myanimelist.net/images/anime/1649/109056.jpg",
      "year": 2020,
      "season": "Fall",
      "studio": "Tezuka Productions",
      "source": "Light Novel",
      "genres": ["Girls Love"],
      "themes": ["School"],
      "demographic": "",
      "episodes": [
        { "episode": 1, "score": 4.3 },
        { "episode": 2, "score": 4.6 },
        { "episode": 3, "score": 4.3 },
        { "episode": 4, "score": 4.5 },
        { "episode": 5, "score": 4.5 },
        { "episode": 6, "score": 4.5 },
        { "episode": 7, "score": 4.5 },
        { "episode": 8, "score": 4.3 },
        { "episode": 9, "score": 4.6 },
        { "episode": 10, "score": 4.4 },
        { "episode": 11, "score": 4.6 },
        { "episode": 12, "score": 4.2 }
      ]
    },
    {
      "id": "bocchi",
      "title": "Bocchi the Rock!",
      "cover": "https://cdn.myanimelist.net/images/anime/1448/127956.jpg",
      "year": 2022,
      "season": "Fall",
      "studio": "CloverWorks",
      "source": "Manga",
      "genres": ["Comedy"],
      "themes": ["CGDCT", "Music"],
      "demographic": "Seinen",
      "episodes": [
        { "episode": 1, "score": 4.4 },
        { "episode": 2, "score": 4.4 },
        { "episode": 3, "score": 4.4 },
        { "episode": 4, "score": 4.5 },
        { "episode": 5, "score": 4.6 },
        { "episode": 6, "score": 4.6 },
        { "episode": 7, "score": 4.5 },
        { "episode": 8, "score": 4.7 },
        { "episode": 9, "score": 4.5 },
        { "episode": 10, "score": 4.5 },
        { "episode": 11, "score": 4.6 },
        { "episode": 12, "score": 4.7 }
      ]
    },
    {
      "id": "spy-x-family",
      "title": "Spy x Family",
      "cover": "https://cdn.myanimelist.net/images/anime/1441/122795.jpg",
      "year": 2022,
      "season": "Spring",
      "studio": "Wit Studio",
      "source": "Manga",
      "genres": ["Action", "Award Winning", "Comedy"],
      "themes": ["Childcare", "Super Power"],
      "demographic": "Shounen",
      "episodes": [
        { "episode": 1, "score": 4.6 },
        { "episode": 2, "score": 4.7 },
        { "episode": 3, "score": 4.5 },
        { "episode": 4, "score": 4.7 },
        { "episode": 5, "score": 4.5 },
        { "episode": 6, "score": 4.6 },
        { "episode": 7, "score": 4.6 },
        { "episode": 8, "score": 4.5 },
        { "episode": 9, "score": 4.5 },
        { "episode": 10, "score": 4.5 },
        { "episode": 11, "score": 4.5 },
        { "episode": 12, "score": 4.5 }
      ]
    },
    {
      "id": "blue-spring-ride",
      "title": "Blue Spring Ride",
      "cover": "https://cdn.myanimelist.net/images/anime/8/64813.jpg",
      "year": 2014,
      "season": "Summer",
      "studio": "Production I.G",
      "source": "Manga",
      "genres": ["Romance"],
      "themes": ["Love Polygon", "School"],
      "demographic": "Shoujo",
      "episodes": [
        { "episode": 1, "score": 4.3 },
        { "episode": 2, "score": 4.4 },
        { "episode": 3, "score": 4.4 },
        { "episode": 4, "score": 4.5 },
        { "episode": 5, "score": 4.3 },
        { "episode": 6, "score": 4.6 },
        { "episode": 7, "score": 4.3 },
        { "episode": 8, "score": 4.4 },
        { "episode": 9, "score": 4.3 },
        { "episode": 10, "score": 4.5 },
        { "episode": 11, "score": 4.7 },
        { "episode": 12, "score": 4.4 }
      ]
    },
    {
      "id": "atri",
      "title": "Atri -My Dear Moments-",
      "cover": "https://cdn.myanimelist.net/images/anime/1825/143408.jpg",
      "year": 2024,
      "season": "Summer",
      "studio": "TROYCA",
      "source": "Visual Novel",
      "genres": ["Drama", "Romance", "Sci-Fi"],
      "themes": [],
      "demographic": "",
      "episodes": [
        { "episode": 1, "score": 4.2 },
        { "episode": 2, "score": 4.3 },
        { "episode": 3, "score": 4.3 },
        { "episode": 4, "score": 4.4 },
        { "episode": 5, "score": 4.5 },
        { "episode": 6, "score": 4.5 },
        { "episode": 7, "score": 4.3 },
        { "episode": 8, "score": 4.3 },
        { "episode": 9, "score": 4.4 },
        { "episode": 10, "score": 4.7 },
        { "episode": 11, "score": 4.3 },
        { "episode": 12, "score": 4.2 },
        { "episode": 13, "score": 4.3 }
      ]
    },
    {
      "id": "chunibyo",
      "title": "Love, Chunibyo & Other Delusions!",
      "cover": "https://cdn.myanimelist.net/images/anime/1905/142840.jpg",
      "year": 2012,
      "season": "Fall",
      "studio": "Kyoto Animation",
      "source": "Light Novel",
      "genres": ["Comedy", "Romance"],
      "themes": ["School"],
      "demographic": "",
      "episodes": [
        { "episode": 1, "score": 4.4 },
        { "episode": 2, "score": 4.5 },
        { "episode": 3, "score": 4.5 },
        { "episode": 4, "score": 4.5 },
        { "episode": 5, "score": 4.7 },
        { "episode": 6, "score": 4.6 },
        { "episode": 7, "score": 4.7 },
        { "episode": 8, "score": 4.7 },
        { "episode": 9, "score": 4.8 },
        { "episode": 10, "score": 4.8 },
        { "episode": 11, "score": 4.6 },
        { "episode": 12, "score": 4.5 }
      ]
    },
    {
      "id": "your-lie-april",
      "title": "Your Lie in April",
      "cover": "https://cdn.myanimelist.net/images/anime/3/67177.jpg",
      "year": 2014,
      "season": "Fall",
      "studio": "A-1 Pictures",
      "source": "Manga",
      "genres": ["Drama", "Romance"],
      "themes": ["Love Polygon", "Music", "Performing Arts", "School"],
      "demographic": "Shounen",
      "episodes": [
        { "episode": 1, "score": 4.3 },
        { "episode": 2, "score": 4.5 },
        { "episode": 3, "score": 4.4 },
        { "episode": 4, "score": 4.7 },
        { "episode": 5, "score": 4.4 },
        { "episode": 6, "score": 4.5 },
        { "episode": 7, "score": 4.4 },
        { "episode": 8, "score": 4.6 },
        { "episode": 9, "score": 4.5 },
        { "episode": 10, "score": 4.7 },
        { "episode": 11, "score": 4.6 },
        { "episode": 12, "score": 4.4 },
        { "episode": 13, "score": 4.7 },
        { "episode": 14, "score": 4.6 },
        { "episode": 15, "score": 4.5 },
        { "episode": 16, "score": 4.5 },
        { "episode": 17, "score": 4.5 },
        { "episode": 18, "score": 4.7 },
        { "episode": 19, "score": 4.5 },
        { "episode": 20, "score": 4.6 },
        { "episode": 21, "score": 4.7 },
        { "episode": 22, "score": 4.7 }
      ]
    },
    {
      "id": "buddy_daddies",
      "title": "Buddy Daddies",
      "cover": "https://cdn.myanimelist.net/images/anime/1553/133767.jpg",
      "year": 2023,
      "season": "Winter",
      "studio": "P.A. Works",
      "source": "Original",
      "genres": ["Action", "Comedy"],
      "themes": ["Childcare", "Organized Crime"],
      "demographic": "",
      "episodes": [
        { "episode": 1, "score": 4.3 },
        { "episode": 2, "score": 4.1 },
        { "episode": 3, "score": 4.4 },
        { "episode": 4, "score": 4.5 },
        { "episode": 5, "score": 4.5 },
        { "episode": 6, "score": 4.6 },
        { "episode": 7, "score": 4.6 },
        { "episode": 8, "score": 4.6 },
        { "episode": 9, "score": 4.6 },
        { "episode": 10, "score": 4.6 },
        { "episode": 11, "score": 4.5 },
        { "episode": 12, "score": 4.6 }
      ]
    },
    {
      "id": "protocol-rain",
      "title": "Protocol: Rain",
      "cover": "https://cdn.myanimelist.net/images/anime/1160/138465.jpg",
      "year": 2023,
      "season": "Fall",
      "studio": "Quad",
      "source": "Original",
      "genres": ["Action"],
      "themes": ["Video Game"],
      "demographic": "",
      "episodes": [
        { "episode": 1, "score": 3.4 },
        { "episode": 2, "score": 3.9 },
        { "episode": 3, "score": 3.9 },
        { "episode": 4, "score": 3.8 },
        { "episode": 5, "score": 3.8 },
        { "episode": 6, "score": 3.7 },
        { "episode": 7, "score": 4 },
        { "episode": 8, "score": 4 },
        { "episode": 9, "score": 3.9 },
        { "episode": 10, "score": 4 },
        { "episode": 11, "score": 3.7 },
        { "episode": 12, "score": 3.9 }
      ]
    },
    {
      "id": "the-mystic-archives-of-dantalian",
      "title": "The Mystic Archives of Dantalian",
      "cover": "https://cdn.myanimelist.net/images/anime/2/52683.jpg",
      "year": 2011,
      "season": "Summer",
      "studio": "Gainax",
      "source": "Light Novel",
      "genres": ["Action", "Mystery", "Supernatural"],
      "themes": ["Detective", "Historical"],
      "demographic": "",
      "episodes": [
        { "episode": 1, "score": 4 },
        { "episode": 2, "score": 3.8 },
        { "episode": 3, "score": 3.8 },
        { "episode": 4, "score": 4.2 },
        { "episode": 5, "score": 3.7 },
        { "episode": 6, "score": 4.2 },
        { "episode": 7, "score": 4.1 },
        { "episode": 8, "score": 4 },
        { "episode": 9, "score": 3.9 },
        { "episode": 10, "score": 4 },
        { "episode": 11, "score": 4.1 },
        { "episode": 12, "score": 4.1 }
      ]
    },
    {
      "id": "gosick",
      "title": "Gosick",
      "cover": "https://cdn.myanimelist.net/images/anime/11/27906.jpg",
      "year": 2011,
      "season": "Winter",
      "studio": "Bones",
      "source": "Light Novel",
      "genres": ["Drama", "Mystery", "Romance"],
      "themes": ["Historical"],
      "demographic": "",
      "episodes": [
        { "episode": 1, "score": 4 },
        { "episode": 2, "score": 4.4 },
        { "episode": 3, "score": 4.5 },
        { "episode": 4, "score": 4.3 },
        { "episode": 5, "score": 4.4 },
        { "episode": 6, "score": 4.4 },
        { "episode": 7, "score": 4.5 },
        { "episode": 8, "score": 4.4 },
        { "episode": 9, "score": 4.5 },
        { "episode": 10, "score": 4.5 },
        { "episode": 11, "score": 4.3 },
        { "episode": 12, "score": 4.4 },
        { "episode": 13, "score": 4.4 },
        { "episode": 14, "score": 4.3 },
        { "episode": 15, "score": 4.7 },
        { "episode": 16, "score": 4.5 },
        { "episode": 17, "score": 4.6 },
        { "episode": 18, "score": 4.6 },
        { "episode": 19, "score": 4.5 },
        { "episode": 20, "score": 4.3 },
        { "episode": 21, "score": 4.7 },
        { "episode": 22, "score": 4.6 },
        { "episode": 23, "score": 4.7 },
        { "episode": 24, "score": 4.7 }
      ]
    },
    {
      "id": "bang-dream",
      "title": "BanG Dream!",
      "cover": "https://cdn.myanimelist.net/images/anime/4/82414.jpg",
      "year": 2017,
      "season": "Winter",
      "studio": ["Xebec", "Issen"],
      "source": "Mixed Media",
      "genres": [],
      "themes": ["CGDCT", "Music", "School"],
      "demographic": "",
      "episodes": [
        { "episode": 1, "score": 4.3 },
        { "episode": 2, "score": 4.4 },
        { "episode": 3, "score": 4.1 },
        { "episode": 4, "score": 4.4 },
        { "episode": 5, "score": 4.5 },
        { "episode": 6, "score": 4.3 },
        { "episode": 7, "score": 4.4 },
        { "episode": 8, "score": 4.5 },
        { "episode": 9, "score": 4.4 },
        { "episode": 10, "score": 4.3 },
        { "episode": 11, "score": 4.4 },
        { "episode": 12, "score": 4.7 },
        { "episode": 13, "score": 4.5 }
      ]
    }
  ]
};
